openapi: "3.0.0"
info:
  version: 1.0.0
  title: Todo App
  description: Create and View Todos

  contact:
    name: Ibrahim Khidr
    email: ibrahim.khidr@jumia.com

servers:
  - url: http://localhost:8080/

components:
  schemas:
    Error:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            type: string

    CreateTodoResult:
      properties:
        id:
          type: integer
      required:
        - id

    CreateTodoRequestBody:
      type: object
      properties:
        title:
          type: string
        description:
          type: string          
      required:
        - title

    GetTodoByIdResult:
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        is_done:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - title
        - is_done
        - created_at
        - updated_at

    UpdateTodoResult:
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        is_done:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - title
        - is_done
        - created_at
        - updated_at

    UpdateTodoRequestBody:
      type: object
      properties:
        title:
          type: string
        description:
          type: string   
        is_done:
          type: boolean       


paths:
  '/todo':
    post:
      summary: Create Todo
      operationId: CreateTodo
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/CreateTodoRequestBody"
      responses:
        '201':
          description: Todo Created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/CreateTodoResult'
        '400':
          description: Bad Request Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        'default':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/todo/{id}':
    get:
      summary: Get Todo By Id
      operationId: GetTodoById
      parameters:
        - name: id
          in: path
          description: Todo ID
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Todo Retreived Successfully 
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetTodoByIdResult'
        '400':
          description: Bad Request Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        'default':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update Todo
      operationId: UpdateTodo
      parameters:
        - name: id
          in: path
          description: Todo ID
          required: true
          schema:
            type: integer
            minimum: 1      
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/UpdateTodoRequestBody"
      responses:
        '200':
          description: Todo Updated
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UpdateTodoResult'
        '400':
          description: Bad Request Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        'default':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'      
