// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	item "khidr/todo/interfaces/api/item"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddItemToTodo provides a mock function with given fields: reqParam, reqbody
func (_m *Service) AddItemToTodo(reqParam item.TodoIdRequestUri, reqbody item.AddItemToTodoRequestBody) (*item.ItemIdResult, error) {
	ret := _m.Called(reqParam, reqbody)

	var r0 *item.ItemIdResult
	if rf, ok := ret.Get(0).(func(item.TodoIdRequestUri, item.AddItemToTodoRequestBody) *item.ItemIdResult); ok {
		r0 = rf(reqParam, reqbody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*item.ItemIdResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(item.TodoIdRequestUri, item.AddItemToTodoRequestBody) error); ok {
		r1 = rf(reqParam, reqbody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteItem provides a mock function with given fields: req
func (_m *Service) DeleteItem(req item.ItemIdTodoIdRequestUri) (*item.ItemIdResult, error) {
	ret := _m.Called(req)

	var r0 *item.ItemIdResult
	if rf, ok := ret.Get(0).(func(item.ItemIdTodoIdRequestUri) *item.ItemIdResult); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*item.ItemIdResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(item.ItemIdTodoIdRequestUri) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetItem provides a mock function with given fields: req
func (_m *Service) GetItem(req item.ItemIdTodoIdRequestUri) (*item.ItemResult, error) {
	ret := _m.Called(req)

	var r0 *item.ItemResult
	if rf, ok := ret.Get(0).(func(item.ItemIdTodoIdRequestUri) *item.ItemResult); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*item.ItemResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(item.ItemIdTodoIdRequestUri) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
